
name-template: 'Messenger v$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'

template: |
  ## What’s Changed

  $CHANGES
  
  **Full Changelog**: 
  https://github.com/AdityaBavadekar/Messenger/compare/$PREVIOUS_TAG...$RESOLVED_VERSION
  
change-template: '- $TITLE @$AUTHOR (#$NUMBER) $BODY'
