name: Android CI

on:
  push:
    branches: [ "master","dev"]
  pull_request:
    branches: [ "master"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Add data to local.properties
      env: 
         DATA: ${{ secrets.LOCAL_PROPERTIES }}
      run: echo $DATA > ./local.properties
    - name: Create google-services.json 1
      run: touch ./app/src/google-services.json
    - name: Add data to google-services.json
      env: 
         DATA2: ${{ secrets.GOOGLE_SERVICES_JSON }}
      run: echo $DATA2 > ./app/src/google-services.json
    - name: Build with Gradle
      run: ./gradlew assembleDebug
    - name: Save Apk of successful build
      if: ${{ success() }}
      #uses: actions/upload-artifact@v3
      #with:
        #name: Github Actions DebugApk
        #path: '*/'
      run: tree ./app/build/outputs/apk/debug
    - name: Save reports of failed build
      if: ${{ failure() }}
      uses: actions/upload-artifact@v3
      with:
        name: reports
        path: '*/build/reports'
