name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Add data 1
      env: 
         DATA: ${{ secrets.LOCAL_PROPERTIES }}
      run: echo $DATA > ./local.properties
    - name: Create google-services.json
      run: 
          cd /app/debug
          touch google-services.json
    - name: Add data 2
      env: 
         DATA2: ${{ secrets.GOOGLE_SERVICES_JSON }}
      run: echo $DATA2 > /home/runner/work/Messenger/Messenger/app/src/debug/google-services.json
    - name: Build with Gradle
      run: ./gradlew assembleDebug
    - name: Save reports of failed build
      if: ${{ failure() }}
      uses: actions/upload-artifact@v3
      with:
        name: reports
        path: '*/buildReports'
