name: Create Release Draft

on:
  push:
    branches: [ "master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

  draft_release:
     name: Release APK
     needs: build
     permissions:
      # write permission is required to create a github release
        contents: write
      # write permission is required for autolabeler
      # otherwise, read permission is required at least
        pull-requests: read
     runs-on: ubuntu-latest
     steps:
       - name: Create a draft release
         uses: release-drafter/release-drafter@v5
         id: draft_release
        # (Optional) specify config name to use, relative to .github/. Default: release-drafter.yml
        # with:
        #   config-name: my-config.yml
        #   disable-autolabeler: true
         env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
